
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql 
    ports:
      - "5432:5432"

  svelte:
    build:
      context: ./svelte/frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - app

volumes:
  pgdata:

